---
output: html_document
runtime: shiny
---
Question 6:
```{r}
library(tidyverse)
library(shiny)

d = read_csv('titanic.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Line or Scatter Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variable",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Numerical Variable",
        choices = variables_names,
        selected = "Fare"
      ),
      
      selectInput(
        inputId ="var3",
        label = "Select a Categorical Variables",
        choices = variables_names,
        selected = "Sex"
      ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Scatter Plot" = "point",
                               "Line Plot" = "line"),
                   selected = 'point')
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    v3 = input$var3
    
    
    library(ggplot2)
    
    if(input$plot_choice == 'point')
      
    {
      ggplot(d, aes(x = d[[v1]], y = d[[v2]], color = as.factor(d[[v3]])))+
        geom_point()+
        labs(x = v1, y = v2, color = v3)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]], y = d[[v2]], color = as.factor(d[[v3]])))+
        geom_line()+
        labs(x = v1, y = v2, color = v3)
    }
    
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

Question 7:

```{r}
d = read_csv('titanic.csv')

variables_names = names(d)


ui <- fluidPage(
  
  titlePanel("Bar Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variables",
        choices = variables_names,
        selected = "Sex"
      ),
      
      checkboxGroupInput(inputId = "survive", label = "Select Survival Category",
                         choices = names(table(d$Survived)), inline = TRUE),
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    
    d <- d %>% filter(Survived %in% input$survive)
    
    library(ggplot2)
    
    ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
      geom_bar()+
      labs(x = v1, color = v2)
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

Question 8:

```{r}
d = read_csv('titanic.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variables",
        choices = variables_names,
        selected = "Sex"
      ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Density Plot" = "density",
                               "Histogram Plot" = "histogram"),
                   selected = 'line'
    ), 
    
    sliderInput(inputId = "Age",
                "Select Age Range:",
                min = min(d$Age, na.rm=TRUE),
                max = max(d$Age, na.rm=TRUE),
                value= c(0, 100)
    ),
    
    
    checkboxGroupInput(inputId = "survive", label = "Select Survival Category",
                       choices = names(table(d$Survived)), inline = TRUE),
    
    ),
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    
    
    library(ggplot2)
    
    if(input$plot_choice == 'density')
      
    {
      d <- d %>% filter(Survived %in% input$survive, Age>input$Age[1], Age<input$Age[2])
      ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2)
    }
    
    else
    {
      d <- d %>% filter(Survived %in% input$survive, Age>input$Age[1], Age<input$Age[2])
      ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_histogram()+
        labs(x = v1, color = v2)
    }
    
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

Question 9:

```{r}
d = read_csv('https://covidtracking.com/data/download/all-states-history.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "state", label = "Select State Category",
                         c("CA", "FL", "TX", "MA", "OH"), inline = TRUE
      
    ),
    selectInput(
      inputId ="var1",
      label = "Select a Variable",
      choices = variables_names, selected = "date"
    ),
      selectInput(
        inputId ="var2",
        label = "Select a Variable",
        choices = variables_names, selected = "positive"
      ),
      
    sliderInput(inputId = "date",
                "Select Age Range:",
                min = min(d$date, na.rm=TRUE),
                max = max(d$date, na.rm=TRUE),
                value= c(min(d$date),max(d$date))
    ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Scatter Plot" = "point",
                               "Line Plot" = "line"),
                   selected = 'point'
      ), 
      

      
      
    ),
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    
    
    library(ggplot2)
    
    if(input$plot_choice == 'point')
      
    {
      d <- d %>% filter(state %in% input$state, date>input$date[1], date<input$date[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_point()+
        labs(x = v1, y = v2)
    }
    
    else
    {
      d <- d %>% filter(state %in% input$state, date>input$date[1], date<input$date[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_line()+
        labs(x = v1, y = v2)
    }
    
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

Question 10:

```{r}
d = read_csv('https://covidtracking.com/data/download/all-states-history.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "dataQualityGrade", label = "Select Data Quality",
                         choices = names(table(d$dataQualityGrade)), inline = TRUE
                         
      ),
      selectInput(
        inputId ="var1",
        label = "Select a Variable",
        choices = variables_names, selected = "date"
      ),
      selectInput(
        inputId ="var2",
        label = "Select a Variable",
        choices = variables_names, selected = "positive"
      ),
      
      sliderInput(inputId = "date",
                  "Select Age Range:",
                  min = min(d$date, na.rm=TRUE),
                  max = max(d$date, na.rm=TRUE),
                  value= c(min(d$date),max(d$date))
      ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Scatter Plot" = "point",
                               "Line Plot" = "line"),
                   selected = 'point'
      ), 
      
      
      
      
    ),
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    
    
    library(ggplot2)
    
    if(input$plot_choice == 'point')
      
    {
      d <- d %>% filter(dataQualityGrade %in% input$dataQualityGrade, date>input$date[1], date<input$date[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_point()+
        labs(x = v1, y = v2)
    }
    
    else
    {
      d <- d %>% filter(dataQualityGrade %in% input$dataQualityGrade, date>input$date[1], date<input$date[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_line()+
        labs(x = v1, y = v2)
    }
    
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

Question 11:

```{r}
d = read_csv('Teams.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "teamID", label = "Select AL East Team",
                         c("BOS", "NYA", "TBA", "BAL", "TOR"), inline = TRUE
                         
      ),
      selectInput(
        inputId ="var1",
        label = "Select a Variable",
        choices = variables_names, selected = "yearID"
      ),
      selectInput(
        inputId ="var2",
        label = "Select a Variable",
        choices = variables_names, selected = "HR"
      ),
      
      sliderInput(inputId = "yearID",
                  "Select Age Range:",
                  min = min(d$yearID, na.rm=TRUE),
                  max = max(d$yearID, na.rm=TRUE),
                  value= c(min(d$yearID),max(d$yearID))
      ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Scatter Plot" = "point",
                               "Line Plot" = "line"),
                   selected = 'point'
      ), 
      
      
      
      
    ),
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    v3 = input$teamID
    
    
    
    library(ggplot2)
    
    if(input$plot_choice == 'point')
      
    {
      d <- d %>% filter(teamID %in% input$teamID, yearID>input$yearID[1], yearID<input$yearID[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_point()+
        labs(x = v1, y = v2)
    }
    
    else
    {
      d <- d %>% filter(teamID %in% input$teamID, yearID>input$yearID[1], yearID<input$yearID[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_line()+
        labs(x = v1, y = v2)
    }
    
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

Question 12:

```{r}
d = read_csv('Teams.csv')

variables_names = names(d)

ui <- navbarPage("Navbar!",
                 tabPanel("AL East Plot",
                          
                          sidebarLayout(
                            
                            sidebarPanel(
                              
                              checkboxGroupInput(inputId = "teamID", label = "Select AL East Team",
                                                 c("BOS", "NYA", "TBA", "BAL", "TOR"), inline = TRUE
                                                 
                              ),
                              selectInput(
                                inputId ="var1",
                                label = "Select a Variable",
                                choices = variables_names, selected = "yearID"
                              ),
                              selectInput(
                                inputId ="var2",
                                label = "Select a Variable",
                                choices = variables_names, selected = "HR"
                              ),
                              
                              sliderInput(inputId = "yearID",
                                          "Select Year Range:",
                                          min = min(d$yearID, na.rm=TRUE),
                                          max = max(d$yearID, na.rm=TRUE),
                                          value= c(min(d$yearID),max(d$yearID))
                              ),
                              
                              radioButtons(inputId = "plot_choice", 
                                           label = h3("Select Plot:"),
                                           choices = c("Scatter Plot" = "point",
                                                       "Line Plot" = "line"),
                                           selected = 'point'
                              ), 
                              
     
                            ),
                            
                            mainPanel(
                              plotOutput(outputId = 'show_plot')
                            )
                          )
                 ),
                 
                 
                 tabPanel("NL East",
                          
                          sidebarLayout(
                            
                            sidebarPanel(
                              
                              checkboxGroupInput(inputId = "NLteamID", label = "Select NL East Team",
                                                 c("ATL", "PHI", "MIA", "NYN", "WAS"), inline = TRUE
                                                 
                              ),
                              selectInput(
                                inputId ="NLvar1",
                                label = "Select a Variable",
                                choices = variables_names, selected = "yearID"
                              ),
                              selectInput(
                                inputId ="NLvar2",
                                label = "Select a Variable",
                                choices = variables_names, selected = "HR"
                              ),
                              
                              sliderInput(inputId = "NLyearID",
                                          "Select Year Range:",
                                          min = min(d$yearID, na.rm=TRUE),
                                          max = max(d$yearID, na.rm=TRUE),
                                          value= c(min(d$yearID),max(d$yearID))
                              ),
                              
                              radioButtons(inputId = "NLplot_choice", 
                                           label = h3("Select Plot:"),
                                           choices = c("Scatter Plot" = "point",
                                                       "Line Plot" = "line"),
                                           selected = 'point'
                              ), 
                              
                            ),
                            
                            mainPanel(
                              plotOutput(outputId = 'show_plot2')
                            )
                          )
                 )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    v3 = input$teamID
    
    
    
    library(ggplot2)
    
    if(input$plot_choice == 'point')
      
    {
      d <- d %>% filter(teamID %in% input$teamID, yearID>input$yearID[1], yearID<input$yearID[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_point()+
        labs(x = v1, y = v2)
    }
    
    else
    {
      d <- d %>% filter(teamID %in% input$teamID, yearID>input$yearID[1], yearID<input$yearID[2])
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_line()+
        labs(x = v1, y = v2)
    }
    
    
    
  })
  
  output$show_plot2 <- renderPlot({
    
    NLv1 = input$NLvar1
    NLv2 = input$NLvar2
    NLv3 = input$NLteamID
    
    
    
    library(ggplot2)
    
    if(input$NLplot_choice == 'point')
      
    {
      d <- d %>% filter(teamID %in% input$NLteamID, yearID>input$NLyearID[1], yearID<input$NLyearID[2])
      ggplot(d, aes(x = d[[NLv1]], y = d[[NLv2]]))+
        geom_point()+
        labs(x = NLv1, y = NLv2)
    }
    
    else
    {
      d <- d %>% filter(teamID %in% input$NLteamID, yearID>input$NLyearID[1], yearID<input$NLyearID[2])
      ggplot(d, aes(x = d[[NLv1]], y = d[[NLv2]]))+
        geom_line()+
        labs(x = NLv1, y = NLv2)
    }
    
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

